### ISSUE TITLE
 Error running notify command: nginx -s reload

### ISSUE THREAD

**Issue by eratio08** [armhf-docker-library/nginx-proxy#1]
Hey,

im getting the following error running the the image 
```
nginx-proxy    | dockergen.1 | 2017/03/03 18:31:30 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-proxy    | dockergen.1 | 2017/03/03 18:31:30 Running 'nginx -s reload'
nginx-proxy    | dockergen.1 | 2017/03/03 18:31:30 Error running notify command: nginx -s reload, exit status 1
```

locking into the image and trying to reload nginx manually results in the following error
`nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:43`

looking into the generated conf I can see that it realy has nothing in the upstream - its some not properly generated

```
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream git.* {
}
server {
	server_name git.*;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://git.*;
	}
}
```

**Comment by djmaze** [comment]
@eratio08 Looks like the Docker container defining the `VIRTUAL_HOST` does not expose any port. 

Or the container does not live on the same Docker network as nginx-proxy. This might happen when using the Docker Compose syntax >= V2. See here for more information: https://github.com/jwilder/nginx-proxy/issues/565#issuecomment-246204721

**Comment by eratio08** [comment]
I'm using the docker compose v2 syntax - Thank you for your help! I see if it works

**Comment by eratio08** [comment]
Adding `network_mode: bridge` to both services in the `docker-compose.yml` fixed the problem. The Containers could not communicate and the nginx-proxy was not connected to the bridge network by default as it should have been.
